### ISSUE TITLE
https://laravel-auditing.com/ is down

### ISSUE THREAD

**Issue by ptums** [owen-it/laravel-auditing#737] opened 2022-08-29 13:55 UTC
| Q                 | A
| ----------------- | ---
| Bug?                     |yes

#### Actual Behaviour

[Laravel Auditing](https://laravel-auditing.com/) is down

#### Expected Behaviour

[Laravel Auditing](https://laravel-auditing.com/) is running

#### Steps to Reproduce

Go to [Laravel Auditing](https://laravel-auditing.com/)

#### Possible Solutions

Checkout ``heroku logs --tail``

**Comment by parallels999** [comment] 2022-09-19 22:14
Duplicate of #708

**Closed** 2022-10-28 12:00 UTC
