### ISSUE TITLE
user registration audit fail

### ISSUE THREAD

**Issue by ctf0** [owen-it/laravel-auditing#374] opened 2018-01-27 23:06 UTC
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| Framework         | Laravel
| Framework version | 5.5.32
| Package version   | 5.0.3
| PHP version       | 7.2.1

#### Actual Behaviour

audit return an exception that `user_id` cant be null after user registration form is submitted and user is saved into db.

#### Expected Behaviour

audit can check if there is already a logged in user ex."admin trying to create new users" & if not then save `user_id` == `auth()->user()->id` as this is now a newly created user

#### Steps to Reproduce

- create new laravel project
- use `php artisan make:auth`
- setup the audit package
- try to register new user

**Comment by quetzyg** [comment] 2018-01-28 18:53
Sorry, but I'm unable to reproduce the error you're reporting.

I followed the steps you provided and I managed to register a new `User` and get an `Audit` record. No exception was thrown in the process.

Besides not showing what exactly you are doing (`User` model, configuration, etc), you also fail to describe all the `Audit` configuration steps, so I'll assume you missed something in the documentation.

Being this an issue on your end, I'm closing this. Feel free to comment if you need help, but you'll have to provide more information.

**Closed by quetzyg** 2018-01-28 18:53 UTC

**Comment by ctf0** [comment] 2018-01-28 19:10
can u at least tell me what might cuz this issue, or where to look for the exception maybe i can figure it out ?

**Comment by quetzyg** [comment] 2018-01-28 19:15
I've spent countless hours documenting all the steps necessary to configure the package [here](http://www.laravel-auditing.com/docs/5.0/general-configuration). Just follow them.

**Comment by ctf0** [comment] 2018-01-28 19:18
its okay, its related to using a foreign-id for `user_id`

thanx for the help

**Comment by ctf0** [comment] 2018-01-28 19:29
@quetzyg 

audit doesnt save the `user_id` on registration, can u plz re-check your db and see if the `user_id` is null or not ?

**Comment by quetzyg** [comment] 2018-01-28 19:34
Of course it doesn't, you don't have a logged `User`, you're registering one. Mine is also `null`, which is expected behaviour.

**Comment by ctf0** [comment] 2018-01-28 19:39
that was the main topic of the ticket

**Comment by quetzyg** [comment] 2018-01-28 19:49
You reported an exception being thrown when auditing (meanwhile, your original text has been edited), and that was a foreign key issue you had.

In regards to the behaviour you want, you'll have to implement it yourself.
