### ISSUE TITLE
Auditing "retrieved" Eloquent events

### ISSUE THREAD

**Issue by yiningzhao** [owen-it/laravel-auditing#343] opened 2017-11-15 22:46 UTC
| Q                 | A
| ----------------- | ---
| Bug?              | no|yes
| New Feature?      | yes
| Framework         | Laravel|Lumen
| Framework version | 5.x.y
| Package version   | 4.x.y
| PHP version       | 5.x.y|7.x.y

#### Actual Behaviour

I checked the documentation and the "retrieved" events are not currently available for auditing. 

#### Possible Solutions

Do you have plans to enable auditing the retrieved events in the future?
If not, can you please give me some pointers on how to implement this feature?

**Comment by quetzyg** [comment] 2017-11-15 23:18
Hey there @yiningzhao,

I was totally unaware of such event (apparently it was added in L5.5).

I'm gonna add support for it in version 5, but it will be off by default (the user will have to set `retrieved` as an audit event), because as you may imagine, this will create lots of audits on busy applications.

Also bear in mind that even if enabled, when caching is in use, the `retrieved` events won't fire.

Thanks for the suggestion!

**Comment by yiningzhao** [comment] 2017-11-16 01:27
Yes I was very happy that they added this new event, because the project that I'm working on requires us to track the retrievals of the records. 

It totally makes sense that this will be off by default. Thank you for mentioning the caching, I will keep that in mind.

I understand that version 5 is in development and could you please give an estimate on when this new feature will be implemented? As I mentioned above, we are using this package for a research project at UCLA and tracking retrievals is a requirement. If you can share your thoughts on when this support will be added that would be great.

**Comment by quetzyg** [comment] 2017-11-16 10:30
Version 5 is pretty much done, the only thing left is updating the documentation. I was aiming at releasing it by the end of this month, or the beginning of next.

I've already got the `retrieved` audit implemented locally, but I'm running into an issue when creating a model, where lots of `retrieved` events seem to be fired, causing a `Fatal error: Maximum function nesting level of '256' reached, aborting!`.

I'll investigate later.

**Comment by quetzyg** [comment] 2017-11-18 21:13
Just to let you know that support for the `retrieved` event is gonna hit the `master`, [soon](https://github.com/owen-it/laravel-auditing/pull/344).

**Comment by quetzyg** [comment] 2017-11-26 17:20
V5 is gonna be tagged this tuesday during [Laravel Lisbon // S01E01](https://www.meetup.com/Laravel-Lisbon/events/245137268/), closing issue and considering it solved.

**Closed by quetzyg** 2017-11-26 17:20 UTC
Labels: enhancement, question

**Comment by quetzyg** [comment] 2018-07-17 08:13
If you're getting a _maximum nest level_ error, it means you're doing something odd in the user model.

I'll have to see the code for all classes involved to know what's actually going on.

**Comment by drmmr763** [comment] 2018-08-02 19:59
Hi @quetzyg 

Sorry it took me so long to get back to this issue was busy with other parts of the project. I'm circling back to this and I am still having the issue. I decided to try to prove whether or not this was an issue with my app code or an issue with the Audit package.

To confirm my theory its an audit package problem here's what I did:
* New fresh laravel install
* Install & configure laravel passport as specified in the docs
* Test the I can `GET /api/user`, the default configured api route

At this point everything is confirmed working.

Next I set up Laravel Auditing:
* Install and configure `Laravel-Auditing`
* added "retrieved" to the audit events
* Test the `GET /api/user` endpoint - this times out (using php artisan serve instead of an xdebug configured box so no max nest error, but same problem)

Here is exactly the code I ran to reproduce the issue:
https://github.com/drmmr763/laravel-auditing-retrieved-bug

Again this is a very stock, plain laravel app out of the box. I've only installed Passport and Audit, and enabled the "retrieved" event in Audit config.

Let me know if I should open a new issue with more details regarding the issue and if I can provide any more details on reproducing.

**Comment by quetzyg** [comment] 2018-08-12 18:05
Hi @drmmr763,

While testing your repo, I did see the issue you mentioned, yet I couldn't really find what was causing it, so I created a new Laravel project:
`composer create-project --prefer-dist laravel/laravel laravel56`

Installed the Auditing package:
`composer require owen-it/laravel-auditing`
`php artisan auditing:install`

Installed the passport package:
`composer require laravel/passport`
`php artisan passport:keys`

Migrate the database:
`php artisan migrate`

Create the auth routes:
`php artisan make:auth`

Check that the routes are all set:
`php artisan route:list`

Then I registered a user, logged out, logged back in. and couldn't find any issues.

**Comment by quetzyg** [comment] 2018-08-12 18:06
Here's the repo: https://github.com/quetzyg/laravel56-passport6-auditing7

**Comment by quetzyg** [comment] 2018-08-13 08:06
Oh actually, I forgot to add `'retrieved',` to the `events` configuration. Will investigate further.

**Comment by quetzyg** [comment] 2018-08-13 11:58
OK, I just got to the bottom of this. The problem is that the `User` is being resolved, and to do that, it needs to be retrieved. By being retrieved a new `retrieved` event gets fired, which will trigger a new `Audit` (which needs to resolve the `User`, so it's a never ending cycle).

To make this work, you'll have to exclude the `retrieved` event when auditing `User` models, like so:

```
    protected $auditEvents = [
        'created',
        'updated',
        'deleted',
        'restored',
    ];
```

I'll add this to the [troubleshooting](http://www.laravel-auditing.com/docs/master/troubleshooting) section.

**Comment by drmmr763** [comment] 2018-08-13 12:47
Hi @quetzyg thanks so much for spending the time to dig into this! I will try out your exclusion rule approach shortly. 

I'm curious to know if you can think of a good way to do this: We basically have a "user profile" page, and we need to track when a user's page is viewed / edited / updated. I was intending on using the retrieved event for this. 

Given the issue with the resolving of the User model, I see some options:

1. Fire the Audit event in the controller when its needed. (This seems the most straight forward but a pain to maintain :( )

2. Create a second model (UserProfile extends User) which gets used instead of the default User model registered to Laravel. Switch all the controller code to the new model and hope that this avoids the recursion.  (Slightly more maintainable as we get the benefit of the default event working; but two classes).

**Comment by quetzyg** [comment] 2018-08-13 13:09
I guess the cleanest approach would be to implement the `UserResolver` (or the `Guard`?) in a way that the `retrieved` event doesn't get fired when fetching the `User`. Events are an `Eloquent` thing, so using the query `Builder` instead, should solve this.

That's what I would do, anyway.
