### ISSUE TITLE
Date object in "new_values" column not handled correctly in "getModified" function

### ISSUE THREAD

**Issue by calvinps** [owen-it/laravel-auditing#455] opened 2018-10-30 16:34 UTC
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.7
| Package version   | 8.0.3
| PHP version       | 7.2

#### Actual Behaviour

I am calling $audit->getModified() on an audit object where the "new_values" column contains the following json (including a date object): `{"post_date":{"date":"2018-09-12 11:00:00.000000","timezone_type":3,"timezone":"UTC"},"selected_date":"2018-09-12"}`
which causes a warning in Illuminate/Database/Eloquent/Concerns/HasAttributes.php `preg_match() expects parameter 2 to be string, array given`

#### Expected Behaviour

I was expecting that dates stored as objects by the Audit model would get serialized and returned without triggering a warning. 

#### Steps to Reproduce

call 'getModified' on an audit object with a date object in the "new_values" column

#### Possible Solutions

Either store the date as a string, or update the "getModified" function to decode the date object properly.

Not sure if I missed something with how to set up Laravel Auditing for dates or if this a bug. Can you please advise either way? Thanks!

**Comment by quetzyg** [comment] 2018-10-30 17:08
Do you have `post_date` in your `$dates` array?

**Comment by calvinps** [comment] 2018-10-30 17:41
Yes, it's in the $dates array on the model being audited.

**Comment by quetzyg** [comment] 2018-10-30 18:00
What if you update the `post_date` in a model, does the value get stored in the `Audit` as an ISO date/time string or a JSON?

**Comment by calvinps** [comment] 2018-10-30 18:04
It gets stored as a JSON in the `Audit` table

**Comment by quetzyg** [comment] 2018-10-30 18:16
Sorry, I can't reproduce such issue. I can only see it happen when the `$dates` array of the model doesn't contain the attribute.

**Comment by quetzyg** [comment] 2018-10-31 16:47
@calvinps, unless there's something else you would like to add, I'm gonna close this issue.

**Closed** 2018-11-01 11:03 UTC
Labels: V8, help wanted

**Comment by spaceemotion** [comment] 2018-11-26 14:10
@quetzyg Hey, I've come across the same issue today, and yes - the date fields are populated in my model(s).

This seems to have happened as we only recently added the column to the dates array, while the audit package already recorded changes as if it were a normal object - thus storing it as JSON.

The "fix" would probably be to check if the date value is actually a JSON object before trying to compare it as a normal string.

**Comment by quetzyg** [comment] 2018-11-26 14:21
Hi @spaceemotion,

Let me see if I understand this correctly. You have another **date** field in your model, which until recently wasn't present in the `$dates` property.

And now that it has been added, you're having trouble when fetching old audits?

**Comment by nenads** [comment] 2019-03-20 23:02
i can verify that issue exists

if your model has cast like this

`/**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
               'starts_at'   => 'datetime:Y-m-d H:i',
           ];`

`$data = [
'starts_at' => now()
];

$myModel::create($data);
and in some place is you do like this
`
