### ISSUE TITLE
Model's all logs are deleted after  v13.6.5 when Threshold is more 0

### ISSUE THREAD

**Issue by giolaza** [owen-it/laravel-auditing#950] opened 2024-06-26 12:16 UTC
### PHP Version

8.1

### Laravel Version

9.52.16

### Package Version

13.6.7

### Description

Default installation used.
On version 13.6.5 was working good, but after updating project to 13.6.7 logs stopped. Downgrade helped 

### Steps To Reproduce

Basic install.
Use 13.6.5 - all is good
Use 13.6.7 - no logs

**Comment by willpower232** [comment] 2024-06-26 12:28
are you able to try 13.6.6 as well? are you able to share your config file?

**Comment by giolaza** [comment] 2024-06-26 13:12
checked 13.6.6 same problem
config file - audit.php is not published (default used)

additionally i see: log created for model in 13.6.5 is deleted for some reason

**Comment by willpower232** [comment] 2024-06-26 13:30
As per #947 this behaviour happens when the `audit.threshold` value is higher than 0. Is your code definitely not changing that one value at any point even if the config file isn't used? Can you output the value from `php artisan tinker` to confirm what it is?

**Comment by giolaza** [comment] 2024-06-26 13:39
![image](https://github.com/owen-it/laravel-auditing/assets/22479232/ec96f1d6-9896-419f-8574-4feae8ff16ee)

**Comment by giolaza** [comment] 2024-06-26 13:44
found issue in 
vendor/owen-it/laravel-auditing/src/Drivers/Database.php
here is db log:
`\Illuminate\Support\Facades\DB::enableQueryLog();
            $model->audits()
                ->latest()
                ->offset($threshold)->limit(PHP_INT_MAX)
                ->delete() > 0;
            $queries = \Illuminate\Support\Facades\DB::getQueryLog();
            dd($queries);`
`delete from `audits` where `audits`.`auditable_type` = ? and `audits`.`auditable_id` = ? and `audits`.`auditable_id` is not null order by `created_at` desc limit 9223372036854775807`

**Comment by giolaza** [comment] 2024-06-26 13:52
https://github.com/owen-it/laravel-auditing/pull/951

**Comment by giolaza** [comment] 2024-06-26 15:15
checked, forgot that in model I set limit for rows 1000000

**Comment by parallels999** [comment] 2024-06-26 15:20
Duplicate of #947

**Comment by erikn69** [comment] 2024-06-26 15:21
Hi, test new changes on #948

**Closed** 2024-06-26 20:56 UTC
Labels: duplicate
