### ISSUE TITLE
configuration & php artisan config:cache : bug

### ISSUE THREAD

**Issue by Grummfy** [owen-it/laravel-auditing#290] opened 2017-08-16 13:49 UTC
| Q                 | A
| ----------------- | ---
| Bug?              | no (for me laravel is bad on this) & yes (because no choice)
| New Feature?      | no
| Framework         | Laravel (Lumen?)
| Framework version | 5.4
| Package version   | 4.1
| PHP version       | *

#### Actual Behaviour

When I use php artisan config:cache, the app crashed.

#### Expected Behaviour

When I use php artisan config:cache, i would like my app still running.

#### Steps to Reproduce

install the package with the config file, and run php artisan config:cache

#### Possible Solutions

Ask them to make closure usable with laravel config?
Until that
implements a OwenIt\Auditing\Contracts\UserResolver with the same content as the closure 

More information: https://github.com/laravel/framework/issues/9625
I totally disagree with the comment that config with closure is bad, but for now there is no good solution for it.

**Comment by quetzyg** [comment] 2017-08-16 13:54
What exactly is your point with this issue?

**Comment by Grummfy** [comment] 2017-08-16 13:56
well because by default the configuration file came with a closure, you can't cache the config (make the app crash). So just update the default config with a default implementation of the resolver in a class.

**Comment by quetzyg** [comment] 2017-08-16 14:40
While having a closure in the configuration won't work once you try to cache, it quicker to start working with the package, having one less thing to worry about at the beginning. Also, the issue is documented in the [troubleshooting](http://www.laravel-auditing.com/docs/4.1/troubleshooting) and [settings](http://www.laravel-auditing.com/docs/4.1/general-settings) sections, along with a few issues here on GitHub (#213, #234, #237, #250, #284).

I'll keep this one open, to remind me to add a comment about it in the configuration file.

**Comment by Grummfy** [comment] 2017-08-16 14:44
well I forget to check the troubleshooting guide ;)
too fast post this issue

**Comment by mikebronner** [comment] 2017-09-13 01:18
I would like to support the idea that this should be fixed. The configuration file should not cause artifacts or errors working with default Laravel functionality.

**Closed** 2017-09-17 16:58 UTC
Labels: duplicate

**Comment by quetzyg** [comment] 2017-09-17 17:02
A `Closure` is no longer set as the default resolver in the configuration.

**Comment by mike23v** [comment] 2017-09-26 03:26
I'm having the following error Illuminate\Database\Query\Builder::check() since you removed the **Closure** as a default resolver in the configuration or in config/audit.php. Can you please help me on this.? Thanks

**Comment by quetzyg** [comment] 2017-09-26 09:33
@mike23v, the `Illuminate\Database\Query\Builder::check()` issue is because you're doing it wrong. I have already addressed that in the issue you opened (#316).
