### ISSUE TITLE
dont use modal accessors for getModified()

### ISSUE THREAD

**Issue by ctf0** [owen-it/laravel-auditing#333] opened 2017-11-04 01:25 UTC
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.5.19
| Package version   | 4.1.4
| PHP version       | 7.2.0RC5

#### Actual Behaviour

so lets say we have something like this in our model

```php
 public function getBackgroundAttribute($value)
{
    return $value ?: 'some url';
}
```

now because the package save the model data from the db, it means that this part wont affect setting the value in neither `new_value` or `old_value`.

however as the `getModified()` atm compare the `new_value` against the accessor, it means that `old_value = null` wont work and you will get an identical values for both `old & new`

```js
// $item
Audit {#3620 ▼
  #guarded: []
  #casts: array:2 [▶]
  #connection: "mysql"
  #table: null
  #primaryKey: "id"
  #keyType: "int"
  +incrementing: true
  #with: []
  #withCount: []
  #perPage: 15
  +exists: true
  +wasRecentlyCreated: false
  #attributes: array:12 [▼
    "old_values" => "{"background":null}"
    "new_values" => "{"background":"some url"}"
    ...
  ]
  #original: array:12 [▶]
  #changes: []
  #dates: []
  #dateFormat: null
  #appends: []
  #dispatchesEvents: []
  #observables: []
  #relations: array:2 [▶]
  #touches: []
  +timestamps: true
  #hidden: []
  #visible: []
  #fillable: []
  #data: array:19 [▶]
  #metadata: array:17 [▶]
  #modified: array:2 [▶]
}

// $item->getModified()
array:1 [▼
  "background" => array:2 [▼
    "new" => "some url"
    "old" => "some url"
  ]
]
```

#### Expected Behaviour

compare against the db values only.

#### Steps to Reproduce

- add an accessor to the editable model
- init an update operation on the same prop

**Comment by quetzyg** [comment] 2017-11-04 01:29
Use the issue template, or I'll just close this. We have rules.

**Comment by ctf0** [comment] 2017-11-04 01:38
updated

**Comment by quetzyg** [comment] 2017-11-06 22:19
The problem is that you default to `"some url"` in the accessor. And only you can sort that.

**Comment by quetzyg** [comment] 2017-11-06 23:56
In any case, I'm gonna close this, because as stated in the [documentation](http://www.laravel-auditing.com/docs/4.1/audit-presentation):
>The `getModified()` method honors all attribute **mutators** and/or **casts** defined in the Auditable model, transforming the data accordingly.

**Closed by quetzyg** 2017-11-06 23:56 UTC

**Comment by ctf0** [comment] 2017-11-07 02:22
accessors & mutators are 2 whole different things.

accessors are more like presenters & the fact that the package use them over whats already in the db is wrong.

i know that its ur package and u r free to do with it what u want, but overlooking a design issue is not the solution.

**Comment by quetzyg** [comment] 2017-11-07 10:13
>accessors & mutators are 2 whole different things.

[Internally](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L424), they're called **get mutators**.

>accessors are more like presenters & the fact that the package use them over whats already in the db is wrong.

So, the Eloquent `getAttributeValue()` method is [wrong](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L332), then?

**Comment by ctf0** [comment] 2017-11-07 10:16
u r correct about `getAttributeValue()`
and i am correct about using the db values not the accessor

anyway i've solved it https://github.com/ctf0/Odin/blob/5760c0f29d508bd0f216c47080d441b8e952082e/src/Odin.php#L33-L34
