### ISSUE TITLE
Bug with listeners and events

### ISSUE THREAD

**Issue by projct1** [owen-it/laravel-auditing#328] opened 2017-10-26 19:58 UTC
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.5.19
| Package version   | 4.1.3
| PHP version       | 7.1.0

### Description
```php
class EventServiceProvider extends ServiceProvider
{
    protected $listen = [
        'App\Events\Order\OrderCreated' => [
            'App\Listeners\Order\MakeReport'
        ]
    ];
}

class MakeReport
{
    public function handle(OrderCreated $event)
    {
        $report = $this->makeReport($event->order);

        $report->orders()->save($event->order);
    }
}

class Order extends Model
{
    protected $dispatchesEvents = ['created' => OrderCreated::class];
}

Order::create($data);
```
As result i have two wrong audit records: 1 is updated and 2 is created: http://joxi.ru/RmzgJENSWJZex2

**Comment by quetzyg** [comment] 2017-10-26 20:20
Hi there @projct1,

I had no idea that from version 5.5, Eloquent models could now be configured with custom events via the `$dispatchesEvents` attribute.

I guess we'll have to take it into account, now.

Thanks for reporting the bug, I'll work on a fix.

**Comment by quetzyg** [comment] 2017-10-29 00:06
Sorry, but I'm unable to reproduce the issue you're having.

What happens if you comment the line:
`$report->orders()->save($event->order);`

?

**Comment by projct1** [comment] 2017-10-29 09:24
```php
class Report extends Model
{
    public function orders()
    {
        return $this->hasMany('App\Order');
    }
}
```

**Comment by projct1** [comment] 2017-10-29 09:43
Audit with event `update` will not inserts in db.

**Comment by quetzyg** [comment] 2017-10-29 09:54
The `update` event does not exist by default, only `updating`, and `updated`. Also, the tests I did with `created` and `updated` in the `$dispatchesEvents` array, worked as expected.

Both events (standard and custom) are fired, but only the standard one triggers an audit.

While the other day I thought we had to take custom events into account, looking at this again with a fresh mind, tells me otherwise.

I mean, why would an event the package knows nothing about trigger an audit?

You're probably creating and updating the `Order` model, so that's why you have two audits.

Also, you didn't answer my previous question.

**Comment by projct1** [comment] 2017-10-29 11:13
> The update event does not exist by default, only updating and updated

Yea, sry, i made a typo.

> Also, you didn't answer my previous question.

Will one `created` audit record.

`$report->orders()->save($event->order);` is updating `report_id` for `Order` model.

**Comment by quetzyg** [comment] 2017-10-29 11:26
>Btw, `report_id` in `$auditExclude` for `Order;`

You can exclude attributes all you want, but an audit will still be created.

This does not look like a bug to me, so I'm gonna close this.

**Closed by quetzyg** 2017-10-29 11:26 UTC

**Comment by projct1** [comment] 2017-10-29 12:43
When `updated` event fires (after `$report->orders()->save($event->order)`) audit model contains this attributes:
```php
  #attributes: array:9 [▼
    "old_values" => "{"admin_id":null,"fio":null,"email":null,"client_confirmed":null,"time":null,"client_comment":null,"amount":null,"bar_id":null,"date":null,"phone":null}"
    "new_values" => "{"admin_id":1,"fio":"\u041a\u0430\u0440\u043f\u043e\u0432\u0430 \u0415\u043a\u0430\u0442\u0435\u0440\u0438\u043d\u0430 \u041c\u0430\u043a\u0441\u0438\u043c\u043e\u0432\u043d\u0430","email":"sermakov@inbox.ru","client_confirmed":true,"time":"18:52","client_comment":"Incidunt sequi consequatur sit voluptatem quia tempore ut. Assumenda enim et alias.","amount":26,"bar_id":307,"date":"2017-10-08 19:06:37","phone":9013572399} ◀"
    "event" => "updated"
    "auditable_id" => 19
    "auditable_type" => "order"
    "admin_id" => 1
    "url" => "http://gb/order"
    "ip_address" => "127.0.0.1"
    "user_agent" => "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0"
  ]
```
Expected behaviour here for `old_values` is `[]`.

**Comment by projct1** [comment] 2017-10-29 12:52
But why at first inserts audit `updated`, not `created`?

**Comment by quetzyg** [comment] 2017-10-29 15:49
You get the `updated` audit first and the `updated` audit second, because your `OrderCreated` event will fire first and only then the Eloquent `created` one will.

And because you're updating the model during the `OrderCreated`, you'll get that audit first, and the created second.

So again, this is not a bug with this package, not even with Laravel. You'll just have to take that into account when you run several events at the same time.

**Comment by projct1** [comment] 2017-10-29 20:13
For solve my problem, i created listener, but cant get auditEvent property...
```php
use OwenIt\Auditing\Events\Auditing;

class AuditingListener
{
    public function handle(Auditing $event)
    {
        return ! ($event->model->wasRecentlyCreated && $event->model->auditEvent == 'updated');
    }
}
```

**Comment by quetzyg** [comment] 2017-10-29 20:22
Why don't you just create the `Order` and the `Report` in one go? Otherwise you'll have to resort to code like that to avoid weird audits.

**Comment by projct1** [comment] 2017-10-29 20:24
No, i need to create new report if he not exists and bind this report to order, or if report already exists, just bind order to existing report...

**Comment by ChrisThompsonTLDR** [comment] 2018-03-30 22:21
I'll chime in on this with a use case to help understand this bug. Users can create a team. `teams.hash` is null when created.

After the team model has saved the record, I have a listener on the model's `saved` event to hash the id and store it.

###TeamController.php
```
public function store(Request $request)
{
    $request->validate([
        'display_name' => 'required|min:4|max:255',
    ]);

    //  make the team
    $team = Team::create(['display_name' => $request->input('display_name')]);

    return back()
        ->with('success', 'Team created successfully.');
}
```

### Models\Team.php
```
namespace App;

use Laratrust\Models\LaratrustTeam;
use App\Events\TeamCreated;
use App\Events\TeamSaved;
use OwenIt\Auditing\Contracts\Auditable;

class Team extends LaratrustTeam implements Auditable
{
    use \OwenIt\Auditing\Auditable;

    protected $fillable = ['display_name'];

    protected $dispatchesEvents = [
        'created' => TeamCreated::class,
        'saved'   => TeamSaved::class,
    ];
}
```

### TeamCreatedListener.php
```
namespace App\Listeners;

use App\Events\TeamCreated;
use Illuminate\Queue\InteractsWithQueue;

use Vinkla\Hashids\Facades\Hashids;

class TeamHash
{
    public function handle(TeamCreated $event)
    {
        //  add data if not set
        if (empty($event->team->hash)) {
            $event->team->name = Hashids::connection('team')->encode($event->team->id);
            $event->team->save();
        }
    }
}
```

This creates database records:

id|user_id|event|auditable_type|auditable_id|old_values|new_values|url|ip_address|user_agent|tags|created_at|updated_at
2|1|updated|App|1|{"display_name":null,"id":null,"name":null}|{"display_name":"Taco Bandits","id":1,"name":"p5r5vy4z"}|http://phplaravel-38433-469235.cloudwaysapps.com/team?|216.169.143.92|Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36|NULL|2018-03-30 18:09:39|2018-03-30 18:09:39
3|1|created|App|1|[]|{"display_name":"Taco Bandits","id":1,"name":"p5r5vy4z"}|http://phplaravel-38433-469235.cloudwaysapps.com/team?|216.169.143.92|Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36|NULL|2018-03-30 18:09:39|2018-03-30 18:09:39

You can see the `created` is after the `updated` when looking at the `id` column.

**Comment by quetzyg** [comment] 2018-04-02 19:34
>I'll chime in on this with a use case to help understand this bug.

Like I've stated a few comments before, this is not a bug, it's just a bad use case. If you feel it's an actual bug, do open an issue [upstream](https://github.com/laravel/framework/), since this is an auditing package, not an event listener/handler one.

I would suggest you to read about concurrency, since that's what it boils down to (two database writes in the same second, will eventually go out of order at some point).

In regards to the `Auditable` type value being stored as `App`, you'll have to show us the whole code so we could understand what you're actually doing.

**Comment by Peter-Krebs** [comment] 2019-09-19 09:33
Instead of waiting for the model to be created and then updating it again, you can listen to `creating`.  
`creating` fires before the model is saved to the database so you can update fields as you wish.  
The call to `->save()` will be not neccessary as the model will be saved after the `creating` event has been processed.

[Model events](https://laravel.com/docs/5.5/eloquent#events)

I haven't yet worked with `$dispatchesEvents`. I worked with [Observers](https://laravel.com/docs/5.5/eloquent#observers) until now. Reacting to the `creating` event should be equal in implementation either way.
