### ISSUE TITLE
Models Casts and Json strings - stop the escaping!

### ISSUE THREAD

**Issue by mfoote** [owen-it/laravel-auditing#460] opened 2018-11-08 17:44 UTC
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | yes
| Framework         | Laravel
| Framework version | 5.7
| PHP version       | 7.2

#### Actual Behaviour

Cast arrays in the model that store as Json strings are escaped when audit is stored.

#### Expected Behaviour

No escapes, it makes it hard to visibly see what changed.

**Comment by quetzyg** [comment] 2018-11-09 09:51
This seems to be a duplicate of #360. Please read the response I gave, since it explains the reason why this happens and why it's something we have no control over.

You could always try to override the [asJson()](https://github.com/laravel/framework/blob/5.7/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L697) method from your models and pass the appropriate flags, so that the data doesn't get escaped.

Something like the following could work:
```php
protected function asJson($value)
{
    return json_encode($value, JSON_UNESCAPED_UNICODE);
}
```

**Closed by quetzyg** 2018-11-09 09:51 UTC
Labels: invalid
