### ISSUE TITLE
How to auditrail Delete with composite key

### ISSUE THREAD

**Issue by caranzojason** [owen-it/laravel-auditing#456] opened 2018-10-31 11:48 UTC
| Q                 | A
| ----------------- | ---
| Bug?                   |yes
| New Feature?      | no
| Framework         | Laravel|Lumen
| Framework version | 5.6
| Package version   | 8.0
| PHP version       | 7.2.8

#### Actual Behaviour
I want to audit if i delete the model with composite key
in Model:     
    protected $primaryKey  =   ['roleID', 'menuPermissionID'];
    public $incrementing = false; 

using model:
$result = $this->model->where('roleID',$roleId)->
 where('menuPermissionID',$menuPermissionID)>firstOrFail();
 $result->delete();

#### Expected Behaviour
it should delete and save to audit trail.
right now there is an error during delete.
however if i used this query
$this->model->where('roleID',$roleId)->delete();
it will delete but it won't audit trail.
current error: array_key_exists(): The first argument should be either a string or an integer

**Comment by quetzyg** [comment] 2018-10-31 12:51
>right now there is an error during delete.

Can you provide the error, or do I have to guess?

**Comment by caranzojason** [comment] 2018-10-31 13:08
> > right now there is an error during delete.
> 
> Can you provide the error, or do I have to guess?

current error: array_key_exists(): The first argument should be either a string or an integer

**Comment by caranzojason** [comment] 2018-10-31 13:35
> Dude, seriously...
> Paste the entire stack trace for god sake. `array_key_exists()` can be in use anywhere!

#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'array_key_exist...', 'E:\\Projects\\Tim...', 315, Array)
#1 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Concerns\HasAttributes.php(315): array_key_exists(Array, Array)
#2 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1350): Illuminate\Database\Eloquent\Model->getAttribute(Array)
#3 E:\Projects\Timeless\TMS-Framework\vendor\owen-it\laravel-auditing\src\Auditable.php(284): Illuminate\Database\Eloquent\Model->getKey()
#4 E:\Projects\Timeless\TMS-Framework\vendor\owen-it\laravel-auditing\src\Drivers\Database.php(19): Timeless\models\APP\RoleMenuPermission->toAudit()
#5 E:\Projects\Timeless\TMS-Framework\vendor\owen-it\laravel-auditing\src\Auditor.php(69): OwenIt\Auditing\Drivers\Database->audit(Object(Timeless\models\APP\RoleMenuPermission))
#6 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(223): OwenIt\Auditing\Auditor->execute(Object(Timeless\models\APP\RoleMenuPermission))
#7 E:\Projects\Timeless\TMS-Framework\vendor\owen-it\laravel-auditing\src\AuditableObserver.php(65): Illuminate\Support\Facades\Facade::__callStatic('execute', Array)
#8 [internal function]: OwenIt\Auditing\AuditableObserver->deleted(Object(Timeless\models\APP\RoleMenuPermission))
#9 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\Events\Dispatcher.php(379): call_user_func_array(Array, Array)
#10 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\Events\Dispatcher.php(209): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}('eloquent.delete...', Array)
#11 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\Events\Dispatcher.php(182): Illuminate\Events\Dispatcher->dispatch('eloquent.delete...', Array, false)
#12 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Concerns\HasEvents.php(162): Illuminate\Events\Dispatcher->fire('eloquent.delete...', Object(Timeless\models\APP\RoleMenuPermission))
#13 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(855): Illuminate\Database\Eloquent\Model->fireModelEvent('deleted', false)
#14 E:\Projects\Timeless\TMS-Framework\app\APP\RoleMenu\RoleMenuPermissionRepository.php(32): Illuminate\Database\Eloquent\Model->delete()
#15 E:\Projects\Timeless\TMS-Framework\app\APP\Role\RoleService.php(122): Timeless\APP\RoleMenu\RoleMenuPermissionRepository->deleteRoleMenuPermission('28', true)
#16 E:\Projects\Timeless\TMS-Framework\app\Http\Controllers\APP\RoleController.php(590): Timeless\APP\Role\RoleService->update('28', Array, Array)
#17 [internal function]: Timeless\Http\Controllers\App\RoleController->update(Object(Illuminate\Http\Request), '28')
#18 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(54): call_user_func_array(Array, Array)
#19 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('update', Array)
#20 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\Routing\Route.php(212): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Timeless\Http\Controllers\App\RoleController), 'update')
#21 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\Routing\Route.php(169): Illuminate\Routing\Route->runController()
#22 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\Routing\Router.php(665): Illuminate\Routing\Route->run()
#23 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#24 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\Routing\Middleware\SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#25 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(151): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\Auth\Middleware\Authenticate.php(43): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#28 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(151): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php(68): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#31 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(151): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#34 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(151): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 E:\Projects\Timeless\TMS-Framework\app\Http\Middleware\Language.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#37 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(151): Timeless\Http\Middleware\Language->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(63): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#40 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(151): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#43 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(151): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(66): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#46 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(151): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#48 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#49 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\Routing\Router.php(667): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#50 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\Routing\Router.php(642): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#51 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\Routing\Router.php(608): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#52 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\Routing\Router.php(597): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#53 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#54 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#55 E:\Projects\Timeless\TMS-Framework\vendor\fideloper\proxy\src\TrustProxies.php(57): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#56 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(151): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#57 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#58 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(31): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#59 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(151): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#60 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#61 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(31): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#62 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(151): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#63 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#64 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ValidatePostSize.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#65 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(151): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#66 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#67 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(62): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#68 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(151): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#69 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#70 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#71 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#72 E:\Projects\Timeless\TMS-Framework\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#73 E:\Projects\Timeless\TMS-Framework\public\index.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#74 E:\Projects\Timeless\TMS-Framework\server.php(21): require_once('E:\\Projects\\Tim...')
#75 {main}

**Comment by caranzojason** [comment] 2018-10-31 13:35
is that enough?

**Comment by quetzyg** [comment] 2018-10-31 13:55
The `getKey()` method from the `Model` is being called in `Auditable`. Since you have the `$primaryKey` value set as an `array` rather than a `string`, when passing the value to the `getAttribute()` method, it blows up. `¯\_(ツ)_/¯`

Duplicate of #416.

**Comment by caranzojason** [comment] 2018-10-31 14:21
> The `getKey()` method from the `Model` is being called in `Auditable`. Since you have the `$primaryKey` value set as an `array` rather than a `string`, when passing the value to the `getAttribute()` method, it blows up. `¯\_(ツ)_/¯`
> 
> Duplicate of #416.
It say's there
Closing due to lack of information.

**Comment by quetzyg** [comment] 2018-10-31 14:25
Yes, it does. Same issue, though.

**Comment by quetzyg** [comment] 2018-10-31 16:46
> why are you saying lack of information?

Because that's what #416 lacks?

> what kind of information you need?

Like in the other issue I mentioned, this seems to be some kind of eloquent extension (that you also didn't bother to mention, btw). Because this doesn't seem to be in high demand (so far, only two people have complained), I won't waste more of my time.

>this should not be close.

Feel free to investigate the issue and continue commenting if you like. If you find a solution do a pull request and we'll review it.

**Closed by quetzyg** 2018-10-31 16:46 UTC
Labels: V6, duplicate

**Comment by caranzojason** [comment] 2018-11-05 07:00
should not be closed in the first place.
https://github.com/owen-it/laravel-auditing/issues/136
can you check that link. it deletes answered by anteriovieira  but that example
is not composite key now the question is how will it delete if it is a model has a composite key

**Comment by quetzyg** [comment] 2018-11-05 08:48
> can you check that link. 

I checked, now what?

>it deletes answered by anteriovieira but that example
> is not composite key

If it's not using composite a key like you do, why do you think it's even related? You're on version 6.x of the package, that conversation was about 3.x. A lot has changed since then.

>now the question is how will it delete if it is a model has a composite key

And how the fuck should I know? You haven't even told us what package you're using for the composite key feature, because as far as I know, Eloquent doesn't support that.

If you still want help, you have one last try to provide valuable information. If you come up with another answer like the previous ones, I will cease trying to help.

**Comment by caranzojason** [comment] 2018-11-05 12:28
nvm i solve it on my own.

**Comment by eapaza** [comment] 2019-05-20 01:32
> nvm i solve it on my own.

Hi @caranzojason, I found a workaround to audit composite key model with this package, if you're still interested, contact me gapaza.espinoza@gmail.com

**Comment by BlumDev92** [comment] 2020-12-18 12:37
Hello everyone,

I'm having also issues with composite keys. I'm using this [Trait](https://github.com/mopo922/LaravelTreats/blob/master/src/Model/Traits/HasCompositePrimaryKey.php) to get Laravel working with composite keys.

But now as soon as I implement the Auditable interface and try to fetch data of a composite key model, it throws an `array_key_exists` exception in the `getAttribute` function of the `HasAttributes` trait.

I debugged for a long time but I can't find the reason why the `$key` is an array when using the `Auditable` interface.

Here is the complete error stack:

```
ErrorException: array_key_exists(): The first argument should be either a string or an integer in file /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php on line 321
Stack trace:
  1. ErrorException-&gt;() /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:321
  2. array_key_exists() /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:321
  3. Illuminate\Database\Eloquent\Model-&gt;getAttribute() /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/HasOneOrMany.php:376
  4. Illuminate\Database\Eloquent\Relations\HasOneOrMany-&gt;getParentKey() /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/HasOneOrMany.php:70
  5. Illuminate\Database\Eloquent\Relations\HasOneOrMany-&gt;addConstraints() /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/MorphOneOrMany.php:51
  6. Illuminate\Database\Eloquent\Relations\MorphOneOrMany-&gt;addConstraints() /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Relation.php:71
  7. Illuminate\Database\Eloquent\Relations\Relation-&gt;__construct() /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/HasOneOrMany.php:46
  8. Illuminate\Database\Eloquent\Relations\HasOneOrMany-&gt;__construct() /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/MorphOneOrMany.php:40
  9. Illuminate\Database\Eloquent\Relations\MorphOneOrMany-&gt;__construct() /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasRelationships.php:433
 10. Illuminate\Database\Eloquent\Model-&gt;newMorphMany() /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasRelationships.php:418
 11. Illuminate\Database\Eloquent\Model-&gt;morphMany() /var/www/html/vendor/owen-it/laravel-auditing/src/Auditable.php:61
 12. App\Models\Basketball\BasketballTeamGame-&gt;audits() /var/www/html/vendor/owen-it/laravel-auditing/src/Drivers/Database.php:28
 13. OwenIt\Auditing\Drivers\Database-&gt;prune() /var/www/html/vendor/owen-it/laravel-auditing/src/Auditor.php:70
 14. OwenIt\Auditing\Auditor-&gt;execute() /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:261
 15. Illuminate\Support\Facades\Facade-&gt;__callStatic() /var/www/html/vendor/owen-it/laravel-auditing/src/AuditableObserver.php:52
 16. OwenIt\Auditing\AuditableObserver-&gt;updated() /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:388
 17. call_user_func_array() /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:388
 18. Illuminate\Events\Dispatcher-&gt;Illuminate\Events\{closure}() /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:218
 19. Illuminate\Events\Dispatcher-&gt;dispatch() /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasEvents.php:189
 20. Illuminate\Database\Eloquent\Model-&gt;fireModelEvent() /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:750
 21. Illuminate\Database\Eloquent\Model-&gt;performUpdate() /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:661
 22. Illuminate\Database\Eloquent\Model-&gt;save() /var/www/html/app/Http/Controllers/Basketball/BasketballGameController.php:566
 23. App\Http\Controllers\Basketball\BasketballGameController-&gt;updateJerseys() /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54
 24. call_user_func_array() /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54
 25. Illuminate\Routing\Controller-&gt;callAction() /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:45
 26. Illuminate\Routing\ControllerDispatcher-&gt;dispatch() /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php:219
 27. Illuminate\Routing\Route-&gt;runController() /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php:176
 28. Illuminate\Routing\Route-&gt;run() /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php:681
 29. Illuminate\Routing\Router-&gt;Illuminate\Routing\{closure}() /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:130
 30. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /var/www/html/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php:43
 31. Illuminate\Auth\Middleware\Authenticate-&gt;handle() /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171
 32. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /var/www/html/vendor/barryvdh/laravel-cors/src/HandleCors.php:36
 33. Barryvdh\Cors\HandleCors-&gt;handle() /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171
 34. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php:41
 35. Illuminate\Routing\Middleware\SubstituteBindings-&gt;handle() /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171
 36. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php:59
 37. Illuminate\Routing\Middleware\ThrottleRequests-&gt;handle() /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171
 38. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:105
 39. Illuminate\Pipeline\Pipeline-&gt;then() /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php:683
 40. Illuminate\Routing\Router-&gt;runRouteWithinStack() /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php:658
 41. Illuminate\Routing\Router-&gt;runRoute() /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php:624
 42. Illuminate\Routing\Router-&gt;dispatchToRoute() /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php:613
 43. Illuminate\Routing\Router-&gt;dispatch() /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:170
 44. Illuminate\Foundation\Http\Kernel-&gt;Illuminate\Foundation\Http\{closure}() /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:130
 45. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /var/www/html/vendor/fideloper/proxy/src/TrustProxies.php:57
 46. Fideloper\Proxy\TrustProxies-&gt;handle() /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171
 47. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:21
 48. Illuminate\Foundation\Http\Middleware\TransformsRequest-&gt;handle() /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171
 49. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php:27
 50. Illuminate\Foundation\Http\Middleware\ValidatePostSize-&gt;handle() /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171
 51. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php:63
 52. Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode-&gt;handle() /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171
 53. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /var/www/html/vendor/barryvdh/laravel-cors/src/HandleCors.php:36
 54. Barryvdh\Cors\HandleCors-&gt;handle() /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:171
 55. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:105
 56. Illuminate\Pipeline\Pipeline-&gt;then() /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:145
 57. Illuminate\Foundation\Http\Kernel-&gt;sendRequestThroughRouter() /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:110
 58. Illuminate\Foundation\Http\Kernel-&gt;handle() /var/www/html/public/index.php:55
```
